volumes:
  db_blog:
  wordpress_vol:

networks:
  wordpress_net:
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABSE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_blog:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:6.4.3
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 8080:80
    networks:
      - wordpress_net
